jobs:
        - job: PrintInfo
          steps:
                  - script: |
                          echo "This is only a branch, this should never run"
                          echo $(System.PullRequest.PullRequestNumber)
                          echo $(System.PullRequest.PullRequestId)
                          echo $(System.PullRequest.IsFork)
                          echo $(System.PullRequest.TargetBranch)
                          echo $(Build.SourceVersionMessage)
                          echo $(Build.RequestedFor)
                          exit 1

        - job: BuildPullRequest
          condition: eq(variables['Build.Reason'], 'PullRequest')
          steps:
                  - script: echo "Maybe building a PR!"
                  - script: env

        - job: BuildStaging
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/master') 
          steps:
                  - script: echo "Building for staging (master branch)!"
                  - script: env

        - job: BuildProduction
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/production') 
          steps:
                  - script: echo "Building for production (production branch)!"
                  - script: env
