jobs:
        - job: BuildPullRequest
          condition: eq(variables['Build.Reason'], 'PullRequest')
          steps:
                  - script: echo "Building a PR!"
                  - script: env

        - job: BuildStaging
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/master') 
          steps:
                  - script: echo "Building for staging (master branch)!"
                  - script: env

        - job: BuildProduction
          condition: eq(variables['Build.SourceBranch'], 'refs/heads/production') 
          steps:
                  - script: echo "Building for production (production branch)!"
                  - script: env
