jobs:
        - job: Build Pull Request
          steps:
                  - script: echo "Building a PR!"
                    condition: eq(variables['Build.Reason'], 'PullRequest')
                  - script: env

        - job: Build Staging
          steps:
                  - script: echo "Building for staging (master branch)!"
                    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master') 
                  - script: env

        - job: Build Production
          steps:
                  - script: echo "Building for production (production branch)!"
                    condition: eq(variables['Build.SourceBranch'], 'refs/heads/production') 
                  - script: env
